name: Snyk Code PR Scan
on: pull_request
jobs:
  snyk-code:
    name: Snyk Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: snyk/actions/setup@master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Snyk Code to check for vulnerabilities
        run: snyk code test --json > snyk.json
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: curl https://raw.githubusercontent.com/adamsnyk/snyk-code-test-handler/master/code_test_report/__main__.py > htmlgen.py
      - run: cat snyk.json | python3 htmlgen.py

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g to-markdown-cli

      - run: html2md -i output.html -o comment.md --gfm

      - run: sed -i -e $'s/Vuln Type/---------------------\\\nVuln Type/g' comment.md

      - uses: maheshrayas/action-pr-comment-delete@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          org: strava-explorer
          repo: segments-explorer-api
          user: 'github-actions[bot]'
          issue: ${{ github.event.number }}

      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: comment.md